In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [21]:
sales = pd.Series([5,3,2,7,3])

In [4]:
sales

0    2
1    3
2    5
dtype: int64

In [7]:
sales[1]

np.int64(3)

In [8]:
sales[0:2]

0    2
1    3
dtype: int64

In [9]:
sales.index

RangeIndex(start=0, stop=3, step=1)

In [10]:
sales.values

array([2, 3, 5])

In [11]:
sales.dtype

dtype('int64')

In [19]:
sales.head()

0    2
1    3
2    5
dtype: int64

In [22]:
sales.sort_values()

2    2
1    3
4    3
0    5
3    7
dtype: int64

In [23]:
sales.count()

np.int64(5)

In [25]:
sales.notnull()

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [26]:
sales_missing = pd.Series([2,None, 5])

In [28]:
sales_missing.fillna(0)

0    2.0
1    0.0
2    5.0
dtype: float64

In [29]:
si = pd.Series(data=[100, 200,300, 400, 500, ], index=list('abcde'))

In [31]:
si

a    100
b    200
c    300
d    400
e    500
dtype: int64

Pandas Data frame

In [33]:
data = pd.DataFrame({
    'Name': ['Anna', 'Ben'],
    'Lemonades': [2,3]
})

In [34]:
data

   Name  Lemonades
0  Anna          2
1   Ben          3

In [35]:
s1 = pd.Series(data=[1,2,3,4,5])
s2 = pd.Series(data=[10,20,30,40,50])

In [36]:
data = pd.DataFrame({
    'C1': s1,
    'C2': s2
})

In [37]:
data

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

In [39]:
data.shape

(5, 2)

Accessing Data

In [44]:
data.dtypes
data.iloc[3]

C1     4
C2    40
Name: 3, dtype: int64

In [45]:
data.loc[1,'C1']

np.int64(2)

In [48]:
data.iloc[1,1]

np.int64(20)

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C1      5 non-null      int64
 1   C2      5 non-null      int64
dtypes: int64(2)
memory usage: 212.0 bytes

In [50]:
data.describe()

             C1         C2
count  5.000000   5.000000
mean   3.000000  30.000000
std    1.581139  15.811388
min    1.000000  10.000000
25%    2.000000  20.000000
50%    3.000000  30.000000
75%    4.000000  40.000000
max    5.000000  50.000000

Filtering

In [53]:
data[data['C1'] != 2]

   C1  C2
0   1  10
2   3  30
3   4  40
4   5  50

Adding, Updating, Deleting

In [65]:
data['tips'] = [1,2,3,4,5]

In [58]:
data

   C1  C2  tips
0   1  10     1
1   2  20     2
2   3  30     3
3   4  40     4
4   5  50     5

In [ ]:
# del data['tips']
# data

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

In [66]:
data  = data.drop(columns=['tips'])
data

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

In [67]:
data.loc[data['C1'] == 2]=10
data

   C1  C2
0   1  10
1  10  10
2   3  30
3   4  40
4   5  50

In [72]:
data.rename(columns={'C1': 'Column1'}, inplace=True)
data

   Column1  C2
0        1  10
1       10  10
2        3  30
3        4  40
4        5  50

Indexing and selecting

In [73]:
data.set_index("Column1", inplace=True)
data

         C2
Column1
1        10
10       10
3        30
4        40
5        50

In [75]:
data.reset_index(inplace=True)
data

   index  Column1  C2
0      0        1  10
1      1       10  10
2      2        3  30
3      3        4  40
4      4        5  50

Multi Data Index

In [76]:
multi_data = pd.DataFrame({
    'Park': ['A','A','B','B'],
    'Name': ['Anna','Ben','Chris', 'Daisy'],
    'Lemonades': [2,3,4,5]
}).set_index(['Park', 'Name'])

In [77]:
multi_data

            Lemonades
Park Name
A    Anna           2
     Ben            3
B    Chris          4
     Daisy          5

In [79]:
multi_data.query('Lemonades > 3')

            Lemonades
Park Name
B    Chris          4
     Daisy          5

In [80]:
multi_data.to_csv("lemonade_sales.csv")

In [82]:
data1 = pd.read_csv("lemonade_sales.csv")
data1

  Park   Name  Lemonades
0    A   Anna          2
1    A    Ben          3
2    B  Chris          4
3    B  Daisy          5

In [83]:
import numpy as np

dictt = {
    'x':[1,2,3],
    'y':np.array([10,20, 30]),
    'z': 50
}

dictt

{'x': [1, 2, 3], 'y': array([10, 20, 30]), 'z': 50}

In [84]:
pd.DataFrame(dictt)

   x   y   z
0  1  10  50
1  2  20  50
2  3  30  50

In [ ]:
listt  = [[1,2,100],[2,4,100],[3,8,100]]
pd.DataFrame(listt, columns=['x','y', 'z'])

   x  y    z
0  1  2  100
1  2  4  100
2  3  8  100

In [90]:
np_arr = np.array([[1,2,100],[2,4,100],[3,8,100]])
pd.DataFrame(np_arr,columns=['a','b','c'])

   a  b    c
0  1  2  100
1  2  4  100
2  3  8  100

Data cleaning and pre-processing

In [96]:
sales_missing_2 = pd.Series([2,None, 5])
sales_missing_2.fillna(5)

0    2.0
1    5.0
2    5.0
dtype: float64

In [97]:
sales_missing_2.mean()

np.float64(3.5)